import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Automation",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head>
        {/* CDN para Recharts */}
     
      
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

        {/* CDN para React */}

      </head>
      <body>{children}</body>
    </html>
  )
}