import type { Metadata } from "next";
import "./globals.css";
import Script from 'next/script';

export const metadata: Metadata = {
  title: "Automation",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head>
        {/* CDN para Recharts */}
        <Script
          src="https://cdn.jsdelivr.net/npm/chart.js"
          strategy="lazyOnload" // O "afterInteractive" si prefieres que se cargue después de que la página esté interactiva
        />
      </head>
      <body>{children}</body>
    </html>
  )
}
